[package]
name = "pipe_serve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
tokio = {version="1.21.2", features=["rt", "macros"]}
warp = "0.3.3"
